# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'h:\QT2VISTA\WindowDemo.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets 
from PyQt5.QtWidgets import QApplication, QMainWindow, QVBoxLayout, QWidget, QPushButton
from pyvistaqt import QtInteractor
import pyvista as pv

class VISTA2QT(object):
    def setupUi(self, VISTA2QT):
        #设置窗口属性
        VISTA2QT.setObjectName("VISTA2QT")
        #设置窗口大小
        VISTA2QT.resize(1316, 805)
        #设置窗口最小大小
        VISTA2QT.setMinimumSize(QtCore.QSize(800, 800))
        #定义中心控件
        self.centralwidget = QtWidgets.QWidget(VISTA2QT)
        self.centralwidget.setObjectName("centralwidget")
        #定义网格布局
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        #设置网格布局位置
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1301, 791))
        #定义表单布局名字
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        #定义表单布局
        self.Layout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.Layout.setContentsMargins(2, 2, 0, 0)
        #设置表单布局名字
        self.Layout.setObjectName("Layout")
        #定义按钮
        self.Bt1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.Bt2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        #定义按钮尺寸策略
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Bt1.sizePolicy().hasHeightForWidth())
        self.Bt1.setSizePolicy(sizePolicy)
        #设置按钮名字
        self.Bt1.setObjectName("Cylinder")
        self.Bt2.setObjectName("Sphere")
        #将按钮添加到表单布局中
        self.Layout.addWidget(self.Bt1, 0, 0, 1, 1, QtCore.Qt.AlignLeft)
        
        #将按钮添加到表单布局中
        self.Layout.addWidget(self.Bt2, 0, 0, 2, 2, QtCore.Qt.AlignTop)
       
        #定义一个widget控件叫VISTA，并将其添加到表单布局中
        self.VISTA = QtWidgets.QWidget(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.VISTA.sizePolicy().hasHeightForWidth())
        self.VISTA.setSizePolicy(sizePolicy)
        self.VISTA.setMinimumSize(QtCore.QSize(400, 400))#设置最小尺寸
        self.VISTA.setMaximumSize(QtCore.QSize(1920, 1080))#设置最大尺寸
        self.VISTA.setLayoutDirection(QtCore.Qt.LeftToRight)
        #设置控件名字
        self.VISTA.setObjectName("VISTA")
       
        # 创建一个PyVista QtInteractor部件并添加到布局中
        self.plotter = QtInteractor(self.VISTA)
        self.plotter.background_color = 'GRAY'
        #plotter放置在VISTA控件中
        
        self.Layout.addWidget(self.VISTA, 0, 1, 1, 1)
         #将控件添加到表单布局中
        VISTA2QT.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(VISTA2QT)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1316, 26))
        self.menubar.setObjectName("菜单栏")
        VISTA2QT.setMenuBar(self.menubar)
        for menu_name in ["File", "Edit", "View", "Tools", "Help"]:
            menu =  self.menubar.addMenu(menu_name)
    
        self.statusbar = QtWidgets.QStatusBar(VISTA2QT)
        #设置状态栏大小
        self.statusbar.setSizeGripEnabled(False)
        self.statusbar.setObjectName("状态栏")
        #状态栏显示文字为"Ready"
        self.statusbar.showMessage("状态")

        VISTA2QT.setStatusBar(self.statusbar)

        self.retranslateUi(VISTA2QT)
        QtCore.QMetaObject.connectSlotsByName(VISTA2QT)

    def retranslateUi(self, VISTA2QT):
        _translate = QtCore.QCoreApplication.translate
        VISTA2QT.setWindowTitle(_translate("VISTA2QT", "VISTA2QT"))
        #设置mainwindow的图标
        VISTA2QT.setWindowIcon(QtGui.QIcon('ICON.png'))
        self.Bt1.setText(_translate("VISTA2QT", "Cylinder","Sphere"))
